env:
  global:
    - secure: Ni7ZNWMiXEkYBvq7LqG2SDf8spFt/y7rKUuhsM4fvMHCv3bwBiuyAqnAwRsfmalKcJgvIrTGfuc8oX/TIR25mUZW3IpQuWqUVWSaETWh+nSGSrEJW9Tk1kfOhe1NfEqKm4v193/spbN12kKV8MSbTwk1rlbf7n5WCyQjIl/lUKM=
language: rust
script:
  - cargo build -v
  - cargo doc --no-deps -v
  - mv target/doc doc
after_script: |
  cargo doc \
  && echo '<meta http-equiv=refresh content=0;url=linenoise/index.html>' > target/doc/index.html && \
  sudo pip install ghp-import && \
  ghp-import -n target/doc && \
  git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
