[package]

name = "linenoise"
version = "0.0.1"
authors = [ "Pierre Baillet <pierre@baillet.name>" ]
build = "build.rs"


[lib]

name = "linenoise"

[[bin]]

name = "linenoise_example"

[build-dependencies]
gcc = "~0.1.0"

